blank_issues_enabled: false
contact_links:
  - name: Ask me anything me on LinkedIn
    url: https://www.linkedin.com/in/jmfayard/
    about: For questions and discussion about ignite
  - name: Career ressources for developers
    url: https://jmfayard.dev/
    about: My substack
  - name: Des Vies De Devs
    url: https://discord.gg/rNTupfnY
    about: Discord Community where we post news, tips, requests for help, and other discussions.