name: Visibility Boost
description: Let's define your career project and share it with the world
labels: ["job-hunting"]
body:
  - type: markdown
    attributes:
      value: >
        ## Quésako ?
            
        Le premier rôle de cette issue est de définir votre projet professionel sous un format qui soit très clair pour les recruteurs
        en répondant à l'avance aux principales questions qu'ils se posent pour se voir si ça vaut le coup ou pas de vous contacter
        et le cas échéant de leur permettre de réserver un créneau sur votre cal.com

        Le second rôle est de fournir une URL centralisée qu'on puisse facilement partager sur LinkedIn / Twitter / les communautés de recruteurs

        Et le tout dans la plus grande transparence !!    
  - type: textarea
    id: tldr
    attributes:
      label: Too Long Didn't Read
      description: Voir l'exemple sur https://github.com/jmfayard/agent-de-devs/issues/10
      placeholder: >
        - Qui? Jean-Michel Fayard
        - Salaire: 65k€
        - Role: Team Lead + Backend Engineer + Agent de développeurs
        - Stack: Spécialiste Java/Kotlin mais ouvert à TypeScript / C# / ...
        - Formation: Diplôme ingénieur Ensimag + Erasmus Karlsruhe en Allemagne
        - Location: Paris, Tours, Berlin, Full Remote
        - Dispo: Immédiate
        - Contrat: CDI ou Freelance
    validations:
      required: true
  - type: textarea
    attributes:
      label: Ce qui me repousse chez une boîte
      description: Also include a description of how to reproduce the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Ce qui m'attire chez une boite
      description: Also include a description of how to reproduce the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comment me contacter
      description: Sous ce thread ? Par email ? Avez-vous un lien cal.com ou calendly ?
    validations:
      required: true

  - type: markdown
    attributes:
      value: >
        ## Avant de partir vérifier que...

        Le titre de l'issue fournit une information complète
        _Jean-Michel recherche une offre de team lead / Dev backend java kotlin / Paris Berlin Fullremote _

        Vous vous êtes connecté avec moi sur LinkedIn
        Vous avez rejoint la communauté Des Vies De Devs
        Voir les liens sur https://github.com/jmfayard/agent-de-devs/issues/new/choose
