name: Visibility Boost
description: Let's define your career project and share it with the world
labels: ["job-hunting"]
body:
  - type: markdown
    attributes:
      value: >
        Le premier rôle de cette issue est de définir votre projet professionel sous un format qui soit très clair pour les recruteurs
        en répondant à l'avance aux principales questions qu'ils se posent pour se voir si ça vaut le coup ou pas de vous contacter
        et le cas échéant de leur permettre de réserver un créneau sur votre cal.com

        Le second rôle est de fournir une URL centralisée qu'on puisse facilement partager sur LinkedIn / Twitter / les communautés de recruteurs

        Et le tout dans la plus grande transparence !!    
  - type: input
    id: nom
    attributes:
      label: Nom
      placeholder: John Doe
    validations:
      required: true

  - type: textarea
    attributes:
      label: Ce qui me repousse chez une boîte
      description: Also include a description of how to reproduce the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Ce qui m'attire chez une boite
      description: Also include a description of how to reproduce the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comment me contacter
      description: Sous ce thread ? Par email ? Avez-vous un lien cal.com ou calendly ?
    validations:
      required: true

