name: Visibility Boost
description: Let's define your career project and share it with the world
labels: ["job-hunting"]
body:
  - type: input
    id: nom
    attributes:
      label: Nom
      placeholder: John Doe
    validations:
      required: true


  - type: markdown
    attributes:
      value: >
        Before creating a **bug report**, please check the following:
          * Ensure you're running the latest version release.
          * Ensure there isn't an existing issue for your bug. If there is, leave a comment on the existing issue.

        If you're unsure whether you've hit a bug, check out the #react-native channel in our [Slack Community](https://community.infinite.red).

  - type: textarea
    attributes:
      label: Ce qui me repousse chez une boîte
      description: Also include a description of how to reproduce the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Ce qui m'attire chez une boite
      description: Also include a description of how to reproduce the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comment me contacter
      description: Sous ce thread ? Par email ? Avez-vous un lien cal.com ou calendly ?
    validations:
      required: true

